version: '3.6'
services:
  journal:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: 'ojs-journal'
    ports:
      - '8080:8080'
      - '8443:8443'
    volumes:
      - ./volumes/public:/var/www/html/public
      - ./volumes/private:/var/www/files
      - ./volumes/plugins:/var/www/html/plugins
      - ./configs/config.inc.php:/var/www/html/config.inc.php
    restart: always
  db:
    image: mysql:latest
    container_name: 'ojs-db'
    environment:
      MYSQL_ROOT_PASSWORD: 'ojsrootpassword'
      MYSQL_DATABASE: 'ojs'
      MYSQL_USER: 'ojs'
      MYSQL_PASSWORD: 'ojsuserpassword'
    ports:
      - '3306:3306'
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: 'phpmyadmin'
    environment:
      PMA_HOST: db
      PMA_ARBITRARY: 1
    ports:
      - '8070:80'
